In [1]:
import numpy as np

In [3]:
a = [2,3, 4]
A = np.array(a)

In [4]:
print(A)

[2 3 4]


In [9]:
b = [0,2, 1]
B = np.array(b)

In [10]:
Add = A + B
print(Add)

[2 5 5]


In [11]:
mul = A*B
print(mul)

[0 6 4]


In [12]:
dot_mul =A.dot(B)

In [13]:
print (dot_mul)


10
