In [2]:
import numpy as np

In [4]:
a = [[1,1,1],[2,2,2]]
A = np.array(a)
print(A)

[[1 1 1]
 [2 2 2]]


In [5]:
b = [[1,0,1],[2,0,2]]
B = np.array(b)
print(B)

[[1 0 1]
 [2 0 2]]


In [7]:
add = A+B
print(add)

[[2 1 2]
 [4 2 4]]


In [8]:
sub =A-B
print(sub)

[[0 1 0]
 [0 2 0]]


In [11]:
mul = A*B
print(mul)

[[1 0 1]
 [4 0 4]]
